social_auth_reddit.settings:
  type: config_object
  label: 'Social Auth Reddit settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    user_agent_string:
      type: string
      label: 'User Agent string'
    scopes:
      type: string
      label: 'Scopes to be requested'
    endpoints:
      type: string
      label: 'API Endpoints to be requested'
